### ISSUE TITLE
Import failed (Postman 4.5.1)

### ISSUE THREAD

**Issue by mrzystem** [luckymarmot/Paw-PostmanImporter#18]
When importing a Postman Dump (JSON) from Postman 4.5.1 I get 

> Exception Line 2580. TypeError: [object Object] is not iterable!

The line in question reads:

`"headers": "clientToken: Cl3SLxObW3N8e4iEZ5sp8Xvxt0AiRBt5zDgBIrifj2nTEnOFWCJWk7cwZwyHqfAgAMQNLHzLbN7I8zsF\naccessToken: 609723ad719825c173f12f7afcd6e950\n",`

I must admit my dump file is 2,4 MB large.

**Comment by JonathanMontane** [comment]
Thanks for the report @mrzystem, could you send the incriminating file to our support team, this should speed the process up by quite a large amount. In any case, we're working on it!

email: support@luckymarmot.com

**Comment by mrzystem** [comment]
Thanks, I have sent the incriminating file to support@luckymarmot.com.

**Comment by JonathanMontane** [comment]
@mrzystem hey, can you download the latest update for Postman? I just tested the file and it worked (it took some time to import though :D).

**Comment by mrzystem** [comment]
@JonathanMontane thanks, I updated and yes, it works!
