### ISSUE TITLE
Import Failed - Unresolved Promise

### ISSUE THREAD

**Issue by atalebagha** [luckymarmot/Paw-PostmanImporter#19]
When trying to import a postman dump file I get the following error:

> **The import Extension has started a JavaScript Promise with no pending callback**

Paw v. 4.0.6
Postman v. 4.4.3
Yosemite

**Comment by atalebagha** [comment]
![screen shot 2016-08-08 at 10 35 07 am](https://cloud.githubusercontent.com/assets/9886105/17489724/5b79a7d0-5d54-11e6-92d2-26ccb673905d.png)

**Comment by atalebagha** [comment]
![screen shot 2016-08-08 at 10 40 01 am](https://cloud.githubusercontent.com/assets/9886105/17489759/80e245e0-5d54-11e6-9fe5-d6ab6db7057e.png)

**Comment by mittsh** [comment]
@atalebagha sorry that seems to be a bug in our importer code… will look into it asap, thanks for the report!

**Comment by JonathanMontane** [comment]
@atalebagha We've pushed a small change that may have fixed the bug, although we aren't quite sure, as we could not reproduce the bug. If nothing changes, would you mind sending us the incriminating file though support?

support@paw.cloud

**Comment by atalebagha** [comment]
Thanks for the support!

Unfortunately I am getting another error:

> A JavaScript exception was raised. Open the Extension Console (under the Window menu) for more information.
>
> Error: Invalid collection format: collections should have a list of requests - foundobject

@JonathanMontane I would have to see if our company policy allows us to share this info.

Here is a snapshot of the console:  
![screen shot 2016-08-09 at 10 23 39 am](https://cloud.githubusercontent.com/assets/9886105/17526280/66771650-5e1b-11e6-94fb-e8b349aefe93.png)

**Comment by JonathanMontane** [comment]
@atalebagha I'll check it out asap

**Comment by atalebagha** [comment]
Is there an email I can send this too?

I'm getting a different error now:

<img width="591" alt="screen shot 2016-09-22 at 1 50 11 pm" src="https://cloud.githubusercontent.com/assets/9886105/18765651/860c1c40-80cb-11e6-97aa-cd2190953de8.png">

**Comment by JonathanMontane** [comment]
@atalebagha You can send your files to support@paw.cloud, I'll be investigating this issue. Thanks for the report
