### ISSUE TITLE
Import Failed - undefined is not an object (evaluating 'importer.createRequestContexts')

### ISSUE THREAD

**Issue by pencildrummer** [luckymarmot/Paw-PostmanImporter#20]
When trying to import a Postman collection i get this error:

<img width="454" alt="schermata 2016-11-09 alle 15 03 13" src="https://cloud.githubusercontent.com/assets/4450251/20141297/fa980d1e-a68f-11e6-8a6e-b5767900acd0.png">

In the console the output of the error is the same:

> `JS Exception Line 162. TypeError: undefined is not an object (evaluating 'importer.createRequestContexts')`

I get the error with both v1 and v2 collection export from Postman.

I tryed to dive into the generated code and also in the PostmanImporter and BaseImporter coffescripts but I didn't figured out exactly why the error occurs.
One thing that I'm sure is that when the importer try to guess if it can import with v1 or v2 the score returned is always `false`, and when it tries to get the corresponding version (`null` version due to `score` being `false`) it doesn't find any version and stops working when tries to call `createRequestContexts` on an undefined `importer` object.

This happens on:
- Paw Version v. 3.0.12
- Paw PostmanImporter v. 2.2.13-rc1
- Postman Mac App v. 4.8.1
- Mac OS Sierra 10.12.1

These are the exported collections:

### Collection v2

[API_dev_v2.postman_collection.txt](https://github.com/luckymarmot/Paw-PostmanImporter/files/580916/API_dev_v2.postman_collection.txt)

```
{
	"variables": [],
	"info": {
		"name": "Dev API",
		"_postman_id": "21ec6f21-ad7e-fa0f-ee33-282c5e1eae7f",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
		{
			"name": "Sign up user",
			"request": {
				"url": "https://example.com/api/",
				"method": "POST",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"m\":\"user\",\n    \"c_code\": \"US\",\n    \"tel\": \"1234567\"\n}"
				},
				"description": "Sign up user"
			},
			"response": []
		}
	]
}
```

### Collection v1
[API_dev_v1.postman_collection.txt](https://github.com/luckymarmot/Paw-PostmanImporter/files/580914/API_dev_v1.postman_collection.txt)

```
{
	"id": "5a88e4fe-af2a-53bd-44a0-37d3c17161f7",
	"name": "Dev API",
	"description": "",
	"order": [
		"e6527eaa-f0fa-e4dd-58af-43d9fa5f7643"
	],
	"folders": [],
	"owner": "533473",
	"hasRequests": true,
	"requests": [
		{
			"id": "e6527eaa-f0fa-e4dd-58af-43d9fa5f7643",
			"name": "Sign up user",
			"description": "Sign up user",
			"collectionId": "5a88e4fe-af2a-53bd-44a0-37d3c17161f7",
			"method": "POST",
			"headers": "",
			"dataMode": "raw",
			"data": [],
			"rawModeData": "{\n    \"m\":\"user\",\n    \"c_code\": \"US\",\n    \"tel\": \"1234567\"\n}",
			"url": "https://example.com/api/",
			"responses": []
		}
	]
}
```

**Comment by JonathanMontane** [comment]
@pencildrummer thanks for the report, I'll look into it immediately!

**Comment by JonathanMontane** [comment]
@pencildrummer, the issue should now be fixed. It can take up to an hour for your extensions to update. You can speed up the process by going to the extensions menu and clicking on the `check for updates` button.

Thanks for the awesomely detailed report! it really helped pin down the issue.
